CREATE TABLE WARD_INFO(
WardNumber INTEGER PRIMARY KEY,
WardName VARCHAR(25),
WardLocation VARCHAR(25),
NumberOfBeds INTEGER,
PhoneExtension INTEGER
)ENGINE = INNODB;

CREATE TABLE WARD_SHIFTS(
ShiftID INTEGER PRIMARY KEY,
Hours VARCHAR(10)
)ENGINE = INNODB;

CREATE TABLE REQUIRED_STAFF(
WardNumber INTEGER REFERENCES WARD_INFO(WardNumber),
ShiftID INTEGER REFERENCES WARD_SHIFTS(ShiftID),
PositionID INTEGER,
AmountNeeded INTEGER,
PRIMARY KEY(WardNumber, ShiftID, PositionID)
)ENGINE = INNODB;

CREATE TABLE WARD_BEDS(
WardNumber INTEGER REFERENCES WARD_INFO(WardNumber),
BedNumber INTEGER,
PRIMARY KEY(WardNumber)
)ENGINE = INNODB;

CREATE TABLE STAFF_ON_WARD(
WardNumber INTEGER REFERENCES WARD_INFO(WardNumber),
StaffNumber INTEGER,
PositionID INTEGER REFERENCES REQUIRED_STAFF(PositionID),
PRIMARY KEY(WardNumber, StaffNumber)
)ENGINE = INNODB;

CREATE TABLE WARD_REQUISITION(
WardNumber INTEGER REFERENCES WARD_INFO(WardNumber),
StaffNumber INTEGER REFERENCES STAFF_ON_WARD(StaffNumber),
ReqNumber INTEGER,
ItemDrugNumber INTEGER,
ItemName VARCHAR(50),
QuantityRequired INTEGER,
DateOrdered DATE,
DateRecieved DATE,
PRIMARY KEY(WardNumber, StaffNumber)
)ENGINE = INNODB;

CREATE TABLE SUPPLIES_USED(
ItemNumber INTEGER,
WardNumber INTEGER REFERENCES WARD_INFO(WardNumber),
QuantityUsed INTEGER,
DateUsed DATE,
PRIMARY KEY(ItemNumber, WardNumber)
)ENGINE = INNODB;
