INSERT INTO WARD_INFO VALUES(0,"First","First Floor",10,000);
INSERT INTO WARD_INFO VALUES(1,"Second","First Floor",15,111);
INSERT INTO WARD_INFO VALUES(2,"Third","First Floor",20,222);
INSERT INTO WARD_INFO VALUES(3,"Fourth","First Floor",25,333);
INSERT INTO WARD_INFO VALUES(4,"Fifth","Second Floor",30,444);
INSERT INTO WARD_INFO VALUES(5,"Sixth","Second Floor",35,555);
INSERT INTO WARD_INFO VALUES(6,"Seventh","Second Floor",40,666);

INSERT INTO WARD_BEDS(
SELECT WardNumber, NumberOfBeds 
FROM WARD_INFO
);

INSERT INTO WARD_SHIFTS VALUES(1,"7-3");
INSERT INTO WARD_SHIFTS VALUES(2,"3-11");
INSERT INTO WARD_SHIFTS VALUES(3,"11-7");